### ISSUE TITLE
Exporting html or xml files to host not working

### ISSUE THREAD

**Issue by orasik** [postmanlabs/newman-docker#80] opened 2017-12-20 10:37 UTC
Hi,
I was following the example in docs:

```
docker run -v ~/collections:/etc/newman -t postman/newman_ubuntu1404 \
    run "HTTPBinNewmanTest.json.postman_collection" \
    --environment="HTTPBinNewmanTestEnv.json.postman_environment" \
    --reporters="html,cli" --reporter-html-export="newman-results.html"
```
The test ran fine without issues but there was not file, I tried the xml output as well with no success then I found the issue. I just removed `=` sign after --reporter-html-export and added /etc/postman to file path and bingo! I can see the file now. Thought of sharing it in case it will help someone.

HTML export:

```
docker run -v ~/collections:/etc/newman -t postman/newman_ubuntu1404 \
    run "HTTPBinNewmanTest.json.postman_collection" \
    --environment="HTTPBinNewmanTestEnv.json.postman_environment" \
    --reporters="html,cli" --reporter-html-export "/etc/postman/results.html"
```

XML Export:

```
docker run -v ~/collections:/etc/newman -t postman/newman_ubuntu1404 \
    run "HTTPBinNewmanTest.json.postman_collection" \
    --environment="HTTPBinNewmanTestEnv.json.postman_environment" \
    --reporters="junit,cli" --reporter-junit-export "/etc/postman/results.xml"
```

**Comment by kunagpal** [comment] 2018-05-25 02:01
Closing as a duplicate of #29

**Closed by kunagpal** 2018-05-25 02:01 UTC
