### ISSUE TITLE
environment variables cannot be found

### ISSUE THREAD

**Issue by saripr** [postmanlabs/newman-docker#94] opened 2018-04-29 20:13 UTC
Running below throws:
 sudo docker run --rm --name="newman" -v ~/tests/tests.json:/tmp/newman -t postman/newman_ubuntu1404 run "collection url" --environment="staging.json"

unable to read data from file "staging.json"
ENOENT: no such file or directory, open 'staging.json'

though the path is correct and json file exists.
Ref: https://github.com/postmanlabs/newman/issues/1514

**Comment by kunagpal** [comment] 2018-04-30 15:03
Closing as a duplicate of postmanlabs/newman#1514

**Closed as completed by kunagpal** 2018-04-30 15:03 UTC
