### ISSUE TITLE
Junit output file name has no effect

### ISSUE THREAD

**Issue by amandabouman** [postmanlabs/newman-docker#79] opened 2017-12-04 19:43 UTC
`--reporter-junit-export="newman-report.xml"`

Using this option from the docs results in my report exporting with the following pattern:
newman-run-report-2017-12-04-19-39-31-910-0.xml

rather than whatever customized file name I've used in the --report-junit-export arg.

**Comment by kunagpal** [comment] 2018-05-25 02:01
Closing as a duplicate of #29

**Closed by kunagpal** 2018-05-25 02:01 UTC
