### ISSUE TITLE
Node version is very old.  Might consider updating this image with latest stable nodejs version (8.9.4 at time of writing)

### ISSUE THREAD

**Issue by Laeconian** [postmanlabs/newman-docker#83] opened 2018-01-05 17:12 UTC
https://github.com/postmanlabs/newman-docker/blob/f14b26ccc884e70efa8f28fcfddff24cf15e5a91/images/ubuntu1404/Dockerfile#L10

**Comment by Laeconian** [comment] 2018-01-05 17:14
This caused me headaches setting up a CI solution for testing using postman collections.

**Comment by kunagpal** [comment] 2018-05-09 11:06
Closing as a duplicate of #30

**Closed by kunagpal** 2018-05-09 11:06 UTC
